### ISSUE TITLE
Source closing too early.

### ISSUE THREAD

**Issue by garnertb** [mojodna/tilelive-cache#5]
I'm getting the following error when serving up an mbtiles source via a tilelive-merge layer with tessera.  The lower the value I use for `closeDelay` the quicker this error happens, but it seems like it always eventually happens (the highest I've set it to is 180). Possibly related to https://github.com/mojodna/tilelive-cache/issues/2, but I'm not sure how I can prevent it.  Any ideas?

```
Error: SQLITE_MISUSE: Database is closed
GET /base_pbf/14/4681/6262.pbf 500 29.023 ms - 1159
Error: SQLITE_MISUSE: Database is closed
    at Database.get (/usr/local/lib/node_modules/mbtiles/node_modules/sqlite3/lib/sqlite3.js:20:25)
    at MBTiles.getTile (/usr/local/lib/node_modules/mbtiles/lib/mbtiles.js:152:14)
    at /usr/local/lib/node_modules/tessera/node_modules/tilelive-cache/index.js:44:16
    at lock (/usr/local/lib/node_modules/tessera/node_modules/tilelive-cache/node_modules/locking-cache/index.js:57:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/tessera/node_modules/tilelive-cache/index.js:43:14)
    at MBTiles.<anonymous> (/usr/local/lib/node_modules/tessera/node_modules/tilelive-cache/node_modules/locking-cache/index.js:85:17)
    at getTile (/usr/local/lib/node_modules/tilelive-merge/index.js:70:20)
    at /usr/local/lib/node_modules/tilelive-merge/index.js:94:18
    at fn (/usr/local/lib/node_modules/tilelive-merge/node_modules/async/lib/async.js:638:34)
    at Object._onImmediate (/usr/local/lib/node_modules/tilelive-merge/node_modules/async/lib/async.js:554:34)
```

**Comment by mojodna** [comment]
A workaround for this is to adjust the source cache size in tessera (the `-S` option) to something that's sufficiently high that none of the sources get closed.

**Comment by mojodna** [comment]
This has me questioning how `tilelive-cache` should be closing sources...

The underlying issue in this specific case is that `tilelive-merge` loads sources when it's initially loaded (rather than loading them [from the cache] on each request), so it hangs on to references even when they've been evicted from the cache (and subsequently closed).

(`tilelive-blend` does the right thing and loads them on each `getTile` request.)

2 ideas come to mind to more generally address the issue (and eliminate the timeout):

1. adopt pool semantics (of unlimited size), where sources are checked out and checked back in when they're done. That way we'll know when all references have been accounted for and sources can be closed. This would require changes to the `tilelive` API though.
2. define a set of "cache lifecycle" events, adopting the `open` and `close` events that are emitted by some tilelive sources. This would require that clients reload sources when they're closed, which would require changes to anything that makes a `tilelive.load()` call.

(1) feels cleaner, though an approach that minimizes API changes is necessary.

**Comment by mojodna** [comment]
Updating to `tilelive-merge@1.0.2` (just published) should improve the situation.
